In [4]:
import os
os.listdir()

['.ipynb_checkpoints',
 'df_handling.ipynb',
 'geocoding_gerry.ipynb',
 'reference',
 'VoterFile.csv',
 'VoterFile10.csv',
 'VoterFile10.xlsx',
 'VoterFile100.csv',
 'VoterFile1000.csv',
 'VoterFile10000.csv',
 'VoterFile100000.csv',
 'VoterFile10_clean.csv',
 'VoterFile40k.csv',
 'VoterFile500.csv']

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('VoterFile10000.csv', low_memory=False)
df

,VOTER_ID,COUNTY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,NAME_SUFFIX,REGISTRATION_DATE,EFFECTIVE_DATE,LAST_UPDATED_DATE,OLD_VOTER_ID,...,Water Conservancy,Water Conservancy 2,Water Conservancy 3,Water Conservation,Water Conservation 2,Water,Water 2,Water Sub,Water Quality Authority,Weed and Pest Control
0,600028381,Park,GILBERT,ARTHUR,ROSS,NaN,11/29/2007,9/23/2014,9/23/2014,NaN,...,47800,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1460048,Denver,CHRISTA,ELIZABETH,TRIFANOFF,NaN,9/10/2012,5/20/2014,11/28/2018,35-268158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,547847,Park,KATHERINE,JANE,MASTROIANNI,NaN,3/31/1994,6/23/2008,11/21/2018,47-4794000177,...,47800,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,601171490,Denver,EVE,VICTORIA,SCOTT,NaN,7/5/2018,9/13/2018,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,200023657,El Paso,YVONNE,CUCHENS,NELSON,NaN,2/19/2008,6/15/2018,12/20/2016,NaN,...,SOU WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,200273982,El Paso,KAELI,LYNN,MORA,NaN,4/14/2010,6/20/2018,11/22/2016,NaN,...,SOU WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,601498361,Jefferson,CONNOR,ANDREW,MATEER,NaN,10/23/2016,11/6/2018,11/29/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,601371738,Weld,TRISTAN,ERIN,OLIVA,NaN,8/16/2016,11/6/2018,11/27/2018,NaN,...,NCWCD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,600390117,Mesa,DORA,VANESSA,GOMEZ,NaN,10/19/2011,11/6/2018,11/20/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRMCD
9,2264586,Mesa,DONALD,LEE,SMITH,NaN,2/3/2006,5/6/2014,11/20/2018,39-118472,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRMCD
10,601185148,Park,JAMES,DAVID,ACKER,NaN,10/12/2015,10/12/2015,11/21/2018,NaN,...,47800,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,545464,Park,TONY,RAY,HUDSON,NaN,10/14/1988,10/14/1988,11/21/2018,47-4700003989,...,47800,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,200200010,Larimer,TERIN,DEARING,DEVOTO NOONAN,NaN,10/1/2018,10/1/2018,11/21/2018,NaN,...,64105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35057
13,2209527,Yuma,MARIA,FRUMENCIA,VILLARREAL,NaN,5/1/2014,11/4/2014,11/26/2018,63-6393000101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PCD
14,601226515,Douglas,RYAN,PATRICK,MCNULTY,NaN,8/26/2016,8/26/2016,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,4023,NaN,NaN,NaN,NaN
15,200270441,Larimer,JOANNA,MARIE,TONGUE,NaN,10/9/2012,10/26/2017,11/22/2016,NaN,...,64105,NaN,NaN,NaN,NaN,64056,NaN,NaN,NaN,35057
16,200113343,Denver,KRISTOPHER,CHASE,KREYMBORG,NaN,9/28/2018,9/28/2018,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,6415286,Weld,LENORA,LEE,RAKOWSKI,NaN,9/17/2008,10/21/2015,11/20/2014,62-160797,...,NCWCD,NaN,NaN,NaN,NaN,NaN,NWCWD,NaN,NaN,NaN
18,600365234,Weld,JORDAN,ALEXANDER,BOYER,NaN,9/22/2011,10/21/2015,11/20/2014,NaN,...,NCWCD,NaN,NaN,NaN,NaN,NaN,NWCWD,NaN,NaN,NaN
19,1602493,Larimer,MERL,WAYNE,RIGLI,NaN,11/18/2005,7/16/2011,11/21/2018,35-263118,...,64105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35057
20,600330248,Mesa,DOROTHY,MARIE,HUNT,NaN,12/13/2010,5/6/2014,11/20/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRMCD
21,3907377,Broomfield,GLORIA,ANN,HERNANDEZ,NaN,5/15/2006,10/26/2018,10/26/2018,64-46013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4265269,Adams,AMY,JO,SUTTON,NaN,10/24/2018,10/24/2018,11/28/2018,30-791454,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,600765387,El Paso,RACHEL,CHRISTINE,PARRISH,NaN,5/13/2013,10/21/2015,11/18/2014,NaN,...,SOU WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,200366121,El Paso,TAMSIN,F,COWDERY,NaN,5/20/2014,5/20/2014,11/27/2018,NaN,...,SOU WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,200341200,Denver,KATIE,MARIE,BECKMANN,NaN,3/30/2016,10/7/2018,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,3554750,Delta,HEATHER,ELAINE,PHILLIPS,NaN,3/5/2017,4/23/2018,6/23/2018,15-1501004315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2608146,Jefferson,JESSE,NaN,RAMERIZ,JR,10/6/2012,9/26/2016,11/29/2018,16-398552,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,5900268,Arapahoe,JILL,LORENE,EICHELE,NaN,6/30/2014,10/24/2018,11/30/2016,18-199319,...,NaN,NaN,NaN,NaN,NaN,3072,NaN,NaN,NaN,NaN
29,3692743,Fremont,SHAWN,DALE,CARROLL,NaN,7/17/2006,5/19/2014,11/21/2018,22-2206000950,...,64128,NaN,NaN,NaN,NaN,22017,NaN,64141,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,6335028,Weld,GREGORY,MATTHEW,HADDOCK,NaN,8/29/2014,11/7/2017,11/27/2018,62-264975,...,NCWCD,NaN,NaN,NaN,NaN,NaN,LTWD,NaN,NaN,NaN
9971,601404704,Pitkin,DENNIS,MICHAEL,MCDERMOTT,NaN,9/13/2016,7/2/2018,11/22/2016,NaN,...,NaN,NaN,NaN,64046,NaN,NaN,NaN,NaN,NaN,NaN
9972,600965633,Douglas,NICHOLAS,WILLIAM,POELMA,NaN,9/20/2014,11/6/2018,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9973,601384987,Larimer,SAMANTHA,MARIE,BAKER,NaN,8/27/2016,11/6/2018,11/21/2018,NaN,...,64105,NaN,NaN,NaN,NaN,35007,NaN,NaN,NaN,35057
9974,4218119,Denver,DAVID,ALAN,HUGHES,NaN,11/3/2009,11/4/2010,11/28/2018,30-800200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9975,3099180,Pueblo,MARY,ELIZABETH,PACHECO,NaN,9/18/1998,10/29/2010,11/29/2018,51-85567,...,12.002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9976,689029,Arapahoe,DEANNA,FAITH STACY,SCOTT,NaN,5/12/2003,4/9/2018,4/10/2018,03-816578,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9977,7886792,Boulder,CHRISTINE,MARIE,ANDERSON,NaN,3/7/1984,11/8/2016,11/28/2018,07-214584,...,64105,NaN,64133,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9978,663435,Arapahoe,MYRA,LEE,ROONEY,NaN,3/11/1988,8/26/2018,11/28/2018,03-417476,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9979,200338364,Larimer,SANDRA,NaN,VACA,NaN,3/4/2011,3/4/2011,11/21/2018,NaN,...,64105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35057
9980,600965214,Denver,VANNAK,NaN,UK,NaN,9/13/2014,10/19/2015,4/1/2015,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9981,736210,Arapahoe,COLLEEN,J,KLAUS,NaN,10/1/2004,9/25/2014,11/28/2018,03-1085086,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64187.0,NaN
9982,601263349,Arapahoe,KATHY,YAJAIRA,FLORES,NaN,3/31/2016,5/10/2017,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9983,5913646,Adams,KIMBERLY,ANN,HOFFMAN,NaN,11/1/2010,11/1/2010,11/28/2018,18-233764,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9984,600778179,Arapahoe,TIFFANY,MARIE,HUDSON,NaN,6/26/2013,6/12/2017,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9985,600790726,Arapahoe,STEPHANIE,PERRY,MEDINA,NaN,9/4/2018,11/5/2018,9/14/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9986,7001570,Jefferson,LISA,RENE,KAUFMAN,NaN,3/22/2011,11/4/2014,11/29/2018,01-200113384,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9987,6316618,Weld,SARAH,JANE,LANE,NaN,3/1/2007,11/4/2014,11/27/2018,62-317018,...,NCWCD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9988,600965467,El Paso,ALLISON,MARIE,POPELAR,NaN,9/21/2014,9/21/2014,11/27/2018,NaN,...,SOU WC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9989,3911252,Broomfield,DOUGLAS,PAUL,PELLER,NaN,10/4/2010,10/4/2010,11/27/2018,64-38780,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9990,600047759,Jefferson,NICOLE,RENEE,BARTA,NaN,11/8/2014,10/1/2018,11/29/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9991,2565864,Arapahoe,CHRISTOPHER,MACLELLAN,WEST,NaN,8/19/2018,8/19/2018,11/28/2018,16-351187,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9992,6948627,Adams,RHONDA,RAE,TOWNSEND,NaN,2/27/1991,8/1/2015,11/28/2018,01-100221711,...,CCWCD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9993,727133,Boulder,LINDA,L,MCMULLEN,NaN,5/1/2014,5/1/2014,11/28/2018,03-120351,...,64105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9994,200210243,Adams,CODY,LEVI,ALEXANDER,NaN,11/25/2008,2/5/2013,3/25/2013,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,601681343,Denver,MICHAEL,NaN,EISSHOFER,NaN,10/18/2017,10/18/2017,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,200289895,Arapahoe,MONTERI,KANTREL,HALL,NaN,10/20/2012,11/6/2015,11/21/2014,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,873001,Arapahoe,RODGER,LEE,SANDERS,NaN,9/8/2004,10/13/2018,11/28/2018,03-1074903,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,601323269,Arapahoe,JOYA,KAY,SIDERS,NaN,6/18/2016,11/8/2016,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,601788188,Mesa,RODNEY,LEE,RODRIQUEZ,NaN,6/5/2018,11/6/2018,11/20/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRMCD

In [11]:
df["ID"] = df.index
df.head()

,VOTER_ID,COUNTY,FIRST_NAME,MIDDLE_NAME,LAST_NAME,NAME_SUFFIX,REGISTRATION_DATE,EFFECTIVE_DATE,LAST_UPDATED_DATE,OLD_VOTER_ID,...,Water Conservancy 2,Water Conservancy 3,Water Conservation,Water Conservation 2,Water,Water 2,Water Sub,Water Quality Authority,Weed and Pest Control,ID
0,600028381,Park,GILBERT,ARTHUR,ROSS,NaN,11/29/2007,9/23/2014,9/23/2014,NaN,...,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1460048,Denver,CHRISTA,ELIZABETH,TRIFANOFF,NaN,9/10/2012,5/20/2014,11/28/2018,35-268158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,547847,Park,KATHERINE,JANE,MASTROIANNI,NaN,3/31/1994,6/23/2008,11/21/2018,47-4794000177,...,47801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,601171490,Denver,EVE,VICTORIA,SCOTT,NaN,7/5/2018,9/13/2018,11/28/2018,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
4,200023657,El Paso,YVONNE,CUCHENS,NELSON,NaN,2/19/2008,6/15/2018,12/20/2016,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [16]:
df1 = df.iloc[:,[-1,19,20,21,22]]
df1

,ID,RESIDENTIAL_ADDRESS,RESIDENTIAL_CITY,RESIDENTIAL_STATE,RESIDENTIAL_ZIP_CODE
0,0,12 S MAIN ST,ALMA,CO,80420
1,1,1715 E 16TH AVE,DENVER,CO,80218
2,2,362 DICK MOUNTAIN DR,BAILEY,CO,80421
3,3,1200 S ONEIDA ST APT 5-208,DENVER,CO,80224
4,4,1830 WOODBURN ST,COLO SPRINGS,CO,80905
5,5,1830 WOODBURN ST,COLO SPRINGS,CO,80905
6,6,5409 S IRIS ST,LITTLETON,CO,80123
7,7,10685 COUNTY ROAD 23,FT LUPTON,CO,80621
8,8,2634 PATTERSON RD,GRAND JUNCTION,CO,81506
9,9,3032 BOOKCLIFF AVE,GRAND JUNCTION,CO,81504
10,10,350 COTTAGE GROVE RD,ALMA,CO,80420
11,11,510 BURLAND DR,BAILEY,CO,80421
12,12,522 E 42ND ST,LOVELAND,CO,80538
13,13,700 W 3RD AVE APT 149,YUMA,CO,80759
14,14,10320 COMMONWEALTH ST # 4305,LONE TREE,CO,80124
15,15,2232 CLIPPER WAY,FORT COLLINS,CO,80524
16,16,3300 S FAIRFAX ST,DENVER,CO,80222
17,17,1500 TIPTON DR APT G1,WINDSOR,CO,80550
18,18,1500 TIPTON DR APT G1,WINDSOR,CO,80550
19,19,5075 APRICOT DR,LOVELAND,CO,80538
20,20,755 GOLDENROD CT,GRAND JUNCTION,CO,81505
21,21,13682 PLASTER PT # 102,BROOMFIELD,CO,80023
22,22,2801 E 120TH AVE APT G303,THORNTON,CO,80233
23,23,370 MCGUIRE ST,COLO SPRINGS,CO,80916
24,24,1115 BOWSER DR,COLO SPRINGS,CO,80909
25,25,968 N BRYANT ST,DENVER,CO,80204
26,26,706 1675 RD,DELTA,CO,81416
27,27,12100 W BERRY AVE,LITTLETON,CO,80127
28,28,7650 S KIT CARSON DR,CENTENNIAL,CO,80122
29,29,910 7TH ST,PENROSE,CO,81240
...,...,...,...,...,...
9970,9970,254 S TAMERA AVE,MILLIKEN,CO,80543
9971,9971,310 LACET CT,ASPEN,CO,81611
9972,9972,10177 WOODROSE CT,HIGHLANDS RANCH,CO,80129
9973,9973,5625 MCKINLEY AVE,LOVELAND,CO,80538
9974,9974,9021 E 33RD AVE,DENVER,CO,80238
9975,9975,240 VETA AVE,PUEBLO,CO,81004
9976,9976,601 S FOREST ST # 110,GLENDALE,CO,80246
9977,9977,225 E 8TH AVE APT C13,LONGMONT,CO,80504
9978,9978,505 TOLEDO ST,AURORA,CO,80011
9979,9979,1632 AVONDALE DR,LOVELAND,CO,80538
9980,9980,1904 S YORK ST APT 404,DENVER,CO,80210
9981,9981,13860 E SARATOGA DR,AURORA,CO,80015
9982,9982,2800 S SYRACUSE WAY # 17-201,DENVER,CO,80231
9983,9983,8260 DELAWARE ST,DENVER,CO,80221
9984,9984,8111 E YALE AVE # 7-301,DENVER,CO,80231
9985,9985,8300 E YALE AVE # 2-106,DENVER,CO,80231
9986,9986,979 MILLER ST # 201,LAKEWOOD,CO,80215
9987,9987,313 BYERS AVE,PLATTEVILLE,CO,80651
9988,9988,8195 OLD EXCHANGE DR,COLO SPRINGS,CO,80920
9989,9989,4345 FAIRWAY LN,BROOMFIELD,CO,80023
9990,9990,1587 S GARRISON ST,LAKEWOOD,CO,80232
9991,9991,4550 CHERRY CREEK SOUTH DR # 2100,GLENDALE,CO,80246
9992,9992,30050 E 149TH CT,BRIGHTON,CO,80603
9993,9993,4565 14TH ST UNIT 210,BOULDER,CO,80304
9994,9994,11675 PENNSYLVANIA ST,NORTHGLENN,CO,80233
9995,9995,818 N LOGAN ST APT 202,DENVER,CO,80203
9996,9996,2181 S TRENTON WAY # 16-105,DENVER,CO,80231
9997,9997,7557 E WARREN CIR # 5-207,DENVER,CO,80231
9998,9998,7660 E WARREN CIR # 8-201,DENVER,CO,80231
9999,9999,2226 STAGECOACH RD,GRAND JUNCTION,CO,81507

In [17]:
df1.to_csv("census_gc_trial_10k.csv", index=False)